### ISSUE TITLE
Memory requirement

### ISSUE THREAD

**Issue by itsazzad** [browscap/browscap#812] opened 2015-10-28 21:17 UTC
What is the minimum memory requirement?
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = -1

PHP Versions
●php_browscap.ini (21,640 KB)
-This is a special version of browscap.ini for PHP users only!
●full_php_browscap.ini (45,485 KB)
-This is a larger version of php_browscap.ini with all the new properties.
●lite_php_browscap.ini (233 KB)
-This is a smaller version of php_browscap.ini file containing major browsers & search engines. This file is adequate for most websites.

**Comment by asgrim** [comment] 2015-10-28 21:48
@itsazzad yes, that's quite likely that the file is too large.

As you're using PHP, we can only support loading the files using [browscap/browscap-php](https://github.com/browscap/browscap-php) I'm afraid.

However, we really do want to reduce the size of the files (which would, in turn resolve this). Therefore this is a duplicate of #542

**Closed by asgrim** 2015-10-28 21:48 UTC
