### ISSUE TITLE
Chrome version on windows 7 not being detected

### ISSUE THREAD

**Issue by hadoopbob** [browscap/browscap#1807] opened 2018-02-13 17:18 UTC
given the user agent string:
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3298.3 Safari/537.36

get back 
browser: Chrome
browserMajorVersion: 0
deviceType: Desktop
platform: Win7

but the version should be 65

**Comment by jaydiablo** [comment] 2018-02-13 17:51
This is a duplicate of #1787, as mentioned there, Chrome 65 will be available in the next browscap release (6028).

**Closed by jaydiablo** 2018-02-13 17:51 UTC
