### ISSUE TITLE
PHP browscap.ini throws error

### ISSUE THREAD

**Issue by cm-mfc** [browscap/browscap#764] opened 2015-10-01 07:50 UTC
Since version #6007:

Warning: get_browser(): Compilation failed: missing terminating ] for character class at offset 22

PHP 5.3

**Comment by asgrim** [comment] 2015-10-01 08:35
Duplicate of #761 - will be fixed in 6008 (I'll release as soon as I can)

**Closed by asgrim** 2015-10-01 08:35 UTC
Labels: bug
