### ISSUE TITLE
Windows 11 is not detected

### ISSUE THREAD

**Issue by Tirador1** [browscap/browscap#3049] opened 2024-06-22 02:11 UTC
Windows 11 is not detected [browscap-java](https://github.com/blueconic/browscap-java) uses your library to create a java library to serve some project, and one of services is BrowsCapField.PLATFORM which is return he name of the OS for example Win10.
the problem is when I use this it give me Win10 instead of Win11 my actual OS, then I searched for a while to see that [This isn't a bug. It's by design for compatibility issues](https://answers.microsoft.com/en-us/windows/forum/all/why-does-windows-11-show-windows-10-as-os-version/2da93b57-951b-4771-a328-36ab5ff685d7).

So I create an issue on browscap-java but they told me to cerate an issue here to solve this problem

**Comment by asgrim** [comment] 2024-06-22 06:04
Duplicate of #2706 - unfortunately there is nothing we can do in Browscap at all, since the correct modern way of detecting user agents is using client hints. See the issue I linked to for more information. Thanks!

**Closed as not planned** 2024-06-22 06:05 UTC
Labels: duplicate, wontfix
