### ISSUE TITLE
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### ISSUE THREAD

**Issue by jd19007** [browscap/browscap#2869] opened 2023-07-04 18:19 UTC
# User agent(s)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
```
<put the FULL user agents here - not just partial UA strings>
```

# Browscap version tested on

<e.g. 6001000 (or 6.1.0)> - full_asp_browscap.ini

# Current result on http://browscap.org/ua-lookup

```
<copy information from http://browscap.org/ua-lookup >
```

# Description / Further information

<describe what the issue is, e.g. the UA is missing, the UA needs correcting etc.>

**Comment by asgrim** [comment] 2023-07-20 05:03
Duplicate of #2827

**Closed as not planned** 2023-07-20 05:03 UTC
Labels: Update Agent, duplicate, help wanted
