### ISSUE TITLE
User Agents with specific wrong strings

### ISSUE THREAD

**Issue by mapanet** [browscap/browscap#808] opened 2015-10-28 05:40 UTC
Will be helpful to include some UA strings that are specific and obviously wrong thing.
Return as "Default Browser" is enough to know is not a legit browser/connection UA.
Like this, where the whole UA string is:

Googlebot
test certificate info

**Comment by asgrim** [comment] 2015-10-28 08:45
The UA `test certificate info` returns Default Browser. `Googlebot` is matched by `googlebot*` to ensure reasonable forwards compatibility. This is essentially a duplicate of #3, so closing this in favour of that.

**Closed** 2015-10-28 08:45 UTC
Labels: bug, duplicate, wishlist
