### ISSUE TITLE
Unable to detect chrome 113 browser version

### ISSUE THREAD

**Issue by jainarvi** [browscap/browscap#2854] opened 2023-05-30 15:28 UTC
**Describe the bug**
Unable to detect chrome 113 browser version

**To Reproduce**
Use chrome 113 version's user Agent string for detecting browser version:

It gives browser version as 0.0

**Expected behavior**
It should give browser version as 113

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113

**Comment by sivann** [comment] 2023-06-17 15:00
Same for Chrome 114.0.5735.133 (Official Build) (arm64).

**Comment by asgrim** [comment] 2023-06-17 15:11
Duplicate of #2827

**Comment by asgrim** [comment] 2023-06-17 15:11
Duplicate of #2827

**Closed as not planned** 2023-06-17 15:11 UTC
Labels: Update Agent, help wanted
