### ISSUE TITLE
Parse Browser-Major-Version Wrong ~

### ISSUE THREAD

**Issue by ldcsaa** [browscap/browscap#2878] opened 2023-07-20 01:15 UTC
***Version: 1.4.0***

***Source Code***
```
final Capabilities caps = uaParser.parse(ua);

jsonUa.put("name", ua);
jsonUa.put("browser", caps.getBrowser().concat(GeneralHelper.isStrNotEmpty(caps.getBrowserMajorVersion()) ? " " + caps.getBrowserMajorVersion() : ""));
jsonUa.put("browserType", caps.getBrowserType());
jsonUa.put("deviceType", caps.getDeviceType());
jsonUa.put("platform", caps.getPlatform().concat(GeneralHelper.isStrNotEmpty(caps.getPlatformVersion()) ? " " + caps.getPlatformVersion() : ""));
```

***Output***
the major version is parsed to `0`
```
       "name" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
"browserType" => "Browser",
    "browser" => "Chrome 0",
 "deviceType" => "Desktop",
   "platform" => "Win10 10.0"
```

**Comment by asgrim** [comment] 2023-07-20 05:01
Duplicate of #2827

**Closed as not planned** 2023-07-20 05:02 UTC
Labels: Update Agent, duplicate
